In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/kavit88/Linear-Regression/main/Churn.csv')
df.head()

,Unnamed: 0,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df.drop(['Unnamed: 0', 'customerID'], axis=1, inplace=True)
df.dropna(inplace=True)

In [4]:
df = pd.get_dummies(df, drop_first=True)
df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,1,0,1,0,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,1,1
3,0,45,42.30,1840.75,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
4,0,2,70.70,151.65,0,0,0,1,0,0,...,0,0,0,0,0,1,0,1,0,1

In [5]:
x = df.drop('Churn_Yes', axis=1)
y = df['Churn_Yes']

s = StandardScaler()
x = s.fit_transform(x)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [6]:
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)

In [7]:
print(accuracy_score(y_test, y_pred))

0.7683013503909026

In [12]:
from sklearn.metrics import confusion_matrix
cs = confusion_matrix(y_test, y_pred)
print(cs)

[[937  96]
 [230 144]]

In [11]:
#                 Actual Values
#                   No   Yes
# Predicted   No    TN   FN
# Values     Yes    FP   TP

# Actual Yes and Predicted No : FN (False Negative)
# [[937, 96]
#  [230, 144]]

# accuracy = (TP+TN)/Total_Samples

# Error rate = 1 - accuracy

In [13]:
acc = (cs[0][0]+cs[1][1])/(cs[0][0]+cs[1][1]+cs[0][1]+cs[1][0])
acc

0.7683013503909026

In [ ]:
#           Predicted Values
#                No   Yes
# Actual   No    TN   FP
# Values  Yes    FN   TP

# Actual Yes and Predicted No : FP (False Negative)
# [[937, 96]
#  [230, 144]]

# accuracy = (TP+TN)/Total_Samples

# Error rate = 1 - accuracy

In [ ]:
# accuracy = (TP+TN)/Total_Samples

# Error rate = 1 - accuracy

# Precision = TP/(TP+FP)   (Predicted Positive ma sachhi ketli hati)

# Sensitivity (Recall) = TP/(TP+FN)   (total positive mathi ketli sachhi positive Predict kari)

# Specificity = TN/(TN+FP)   (total negative mathi ketli sachhi negative Predict kari)

In [3]:
Y_act = pd.DataFrame(['Cat', 'Cat', 'Cat', 'Cat', 'Cat', 'Dog', 'Dog', 'Dog', 'Dog', 'Dog', 'Cat', 'Dog'])
Y_pred = pd.DataFrame(['Cat', 'Dog', 'Cat', 'Cat', 'Cat', 'Dog', 'Cat', 'Cat', 'Dog', 'Dog', 'Dog', 'Cat'])

# by default jupyter alphabetical order ma je 1st aavse ene -ve lese
from sklearn.metrics import confusion_matrix
cs = confusion_matrix(Y_act, Y_pred)
print(cs)

Total_Samples = len(Y_pred)
TP = cs[1][1]
TN = cs[0][0]
FP = cs[0][1]
FN = cs[1][0]

accuracy = (TP+TN)/Total_Samples
error_rate = 1 - accuracy
precision = TP/(TP+FP)
sensitivity = TP/(TP+FN)
specificity = TN/(TN+FP)

print('accuracy:',accuracy)
print('error_rate:',error_rate)
print('precision:',precision)
print('sensitivity:',sensitivity)
print('specificity:',specificity)

[[4 2]
 [3 3]]
accuracy: 0.5833333333333334
error_rate: 0.41666666666666663
precision: 0.6
sensitivity: 0.5
specificity: 0.6666666666666666